// <auto-generated />
using System;
using FindRectangle.Infastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FindRectangle.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200507101742_AddFieldToEntity")]
    partial class AddFieldToEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FindRectangle.Domain.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("PointGroupId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PointGroupId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("FindRectangle.Domain.Entities.PointGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("GroupPoints");
                });

            modelBuilder.Entity("FindRectangle.Domain.Entities.Point", b =>
                {
                    b.HasOne("FindRectangle.Domain.Entities.PointGroup", "PointGroup")
                        .WithMany()
                        .HasForeignKey("PointGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
